GET http://localhost:8000/books
content-type: application/json
###

POST http://localhost:8000/books
content-type: application/json

{
    "id": 4,
    "name": "Book 4",
    "price": 14.50
}
###

PATCH http://localhost:8000/books/4
content-type: application/json

{
    "name": "Book Changed 4"
}
###

DELETE http://localhost:8000/books/4
content-type: application/json